apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-no-sidecar
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-no-sidecar
  template:
    metadata:
      labels:
        app: test-no-sidecar
    spec:
      containers:
      - name: main-container
        image: nginx:latest
